version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "82:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - yii2

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: yii
      MYSQL_USER: yii
      MYSQL_PASSWORD: ajadam
      MYSQL_ROOT_PASSWORD: ajadam
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - yii2

  php:
    container_name: php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    environment:
      XDEBUG_CONFIG: "remote_host=193.168.222.1 remote_enable=1 remote_connect_back=0 idekey=PHPSTORM"
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    links:
      - mysql
    networks:
      - yii2

networks:
  yii2:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 193.168.221.0/28

#Volumes
volumes:
  dbdir:
    driver: local
